<?php
/**
 * @file
 * All module hooks implementation can be found in this file.
 */

/**
 * Implements hook_permission().
 */
function gov_analytics_permission() {
  return array(
    'administer gov analytics' => array(
      'title' => t('Administer Gov Analytics'),
    )
  );
}

/**
 * Implements hook_form().
 * Admin form to configurable welcome message
 */
function gov_analytics_form($form, &$form_state) {
  $form['gov_analytics_agency'] = array(
	'#type' => 'textfield',
	'#title' => t('Agency'),
	'#required' => TRUE,
	'#default_value' => variable_get('gov_analytics_agency', 'unspecified:domain.com'),
    '#description' => t('Required. Agency Custom dimension value.'),
  );
  $form['gov_analytics_subagency'] = array(
	'#type' => 'textfield',
	'#title' => t('Subagency'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_subagency','unspecified:domain.com -domain.com'),
    '#description' => t('Optional, recommended. Sub Agency Custom dimension value.'),
  );
  $form['gov_analytics_ver'] = array(
	'#type' => 'checkbox',
	'#title' => t('Ver'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_ver',1),
    '#description' => t('Optional, default on. Version control; used for diagnostics and testing.'),
  );
  $form['gov_analytics_sp'] = array(
	'#type' => 'textfield',
	'#title' => t('Search Parameter'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_sp'),
    '#description' => t('Optional. Additional search parameters.'),
  );
  $form['gov_analytics_exts'] = array(
	'#type' => 'textfield',
	'#title' => t('Extensions'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_exts'),
    '#description' => t('Optional. Additional download extensions.'),
  );
  $form['gov_analytics_yt'] = array(
	'#type' => 'checkbox',
	'#title' => t('Youtube'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_yt',1),
    '#description' => t('Optional, default on. Enable/Disable YoutTube Tracker.'),
  );
  $form['gov_analytics_sdor'] = array(
	'#type' => 'checkbox',
	'#title' => t('Sdor'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_sdor',1),
    '#description' => t('Optional, default on. If true, cookie will be set as subdomain.domain.com.'),
  );
  $form['gov_analytics_dclink'] = array(
	'#type' => 'checkbox',
	'#title' => t('Dclink'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_dclink',0),
    '#description' => t('Optional, default off. Demographic Data (true/false).'),
  );
  $form['gov_analytics_pua'] = array(
	'#type' => 'textfield',
	'#title' => t('Parallel UA ID'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_pua'),
    '#description' => t('Optional. Google Analytics Parallel UA Tracking ID.'),
  );
  $form['gov_analytics_enhlink'] = array(
	'#type' => 'checkbox',
	'#title' => t('Enhlink'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_enhlink',0),
    '#description' => t('Optional, default off. Enhanced Link Attribution (true/false).'),
  );
  $form['gov_analytics_autotracker'] = array(
	'#type' => 'checkbox',
	'#title' => t('Autotracker'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_autotracker',1),
    '#description' => t('Optional, default on. Enable/Disable AutoTracker.'),
  );
  $form['gov_analytics_optout'] = array(
	'#type' => 'checkbox',
	'#title' => t('Optout'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_optout',0),
    '#description' => t('Optional, default off. Page Opt-Out (true/false).'),
  );
  $form['gov_analytics_maincd'] = array(
	'#type' => 'checkbox',
	'#title' => t('Maincd'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_maincd',1),
    '#description' => t('Optional, default on. Send Custom Dimensions - DAP Tracker (true/false)'),
  );
  $form['gov_analytics_cto'] = array(
	'#type' => 'textfield',
	'#title' => t('Cookie Timeout'),
	'#required' => FALSE,
	'#default_value' => variable_get('gov_analytics_cto','24'),
    '#description' => t('Optional, default 24 (months). Ga cookie expiration in months.'),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_menu().
 */
function gov_analytics_menu() {
  $items['admin/config/system/gov_analytics'] = array(
	'title' => 'Gov Analytics',
	'description' => 'Configure Government-Wide Analytics Tool for Federal Agencies',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('gov_analytics_form'),
	'access arguments' => array('administer gov analytics'),
	'type' => MENU_NORMAL_ITEM,
  );
 
  return $items;
}

/**
 * Implements _add_html_head. Logic to build metatag variables output.
 */

$gov_analytics_settings = array();
$gov_analytics_settings['agency']        = variable_get('gov_analytics_agency', 'unspecified:domain.com');
$gov_analytics_settings['subagency']     = variable_get('gov_analytics_subagency','unspecified:domain.com -domain.com');
$gov_analytics_settings['ver']           = variable_get('gov_analytics_ver',1);
$gov_analytics_settings['sp']            = variable_get('gov_analytics_sp');
$gov_analytics_settings['exts']          = variable_get('gov_analytics_exts');
$gov_analytics_settings['yt']            = variable_get('gov_analytics_yt',1);
$gov_analytics_settings['sdor']          = variable_get('gov_analytics_sdor',1);
$gov_analytics_settings['dclink']        = variable_get('gov_analytics_dclink',0);
$gov_analytics_settings['pua']           = variable_get('gov_analytics_pua');
$gov_analytics_settings['enhlink']       = variable_get('gov_analytics_enhlink',0);
$gov_analytics_settings['autotracker']   = variable_get('gov_analytics_autotracker',1);
$gov_analytics_settings['optout']        = variable_get('gov_analytics_optout',0);
$gov_analytics_settings['maincd']        = variable_get('gov_analytics_maincd',1);
$gov_analytics_settings['cto']           = variable_get('gov_analytics_cto','24');

settype($gov_analytics_settings['ver'], "bool");
settype($gov_analytics_settings['yt'], "bool");
settype($gov_analytics_settings['sdor'], "bool");
settype($gov_analytics_settings['dclink'], "bool");
settype($gov_analytics_settings['enhlink'], "bool");
settype($gov_analytics_settings['autotracker'], "bool");
settype($gov_analytics_settings['optout'], "bool");
settype($gov_analytics_settings['maincd'], "bool");

$gov_analytics_query = '?';
$gov_analytics_query_index = 1;

foreach($gov_analytics_settings as $key => $setting) {
  if (!empty($setting)) {
    if(is_bool($setting) AND $setting) {
      $setting = "true";
    }
    if(is_string($setting) AND !is_array($setting)) {
      $setting = check_plain($setting);
      if($gov_analytics_query_index > 1) {
        $gov_analytics_query = $gov_analytics_query . "&" . $key . '=' . $setting;
	  } else {
	    $gov_analytics_query = $gov_analytics_query . $key . '=' . $setting;
	  }
	  $gov_analytics_query_index++;
    }
  }
}
 
$gov_analytics_markup = '<meta type="text/javascript" id="_fed_an_ua_tag" src="' . $gov_analytics_query . '" />';
$gov_analytics_js = array(
  '#type' => 'markup',
  '#markup' => $gov_analytics_markup,
);
drupal_add_html_head($gov_analytics_js, 'gov_analytics_js');

/**
 * Implements hook_libraries_info().
 *
 * For defining external libraries.
 */
module_load_include('module','libraries');
function gov_analytics_libraries_info() {

  // Expected to be extracted into 'sites/all/libraries/digitalgov_dap'.
  $libraries['digitalgov_dap'] = array(
    'name' => 'Digitalgov DAP',
    'vendor url' => 'http://www.digitalgov.gov/services/dap/analytics-tool-instructions/',
    'download url' => 'https://raw.githubusercontent.com/digital-analytics-program/gov-wide-code/master',
    'version callback' => 'gov_analytics_version_callback',
    'files' => array(
      'js' => array('Universal-Federated-Analytics-Min.js'), 
    ),
  );
  
  function gov_analytics_version_callback() {
    return TRUE;
  }

  return $libraries;
}

if (module_exists('libraries')) {
  libraries_load('digitalgov_dap');
}
